-- MySQL Script generated by MySQL Workbench
-- lun. 16 avril 2018 10:38:15 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`editeur`
-- -----------------------------------------------------
CREATE TABLE `editeur` (
  `id_editeur` INT NOT NULL AUTO_INCREMENT,
  `nom_editeur` TEXT(60) NULL,
  PRIMARY KEY (`id_editeur`));


-- -----------------------------------------------------
-- Table `mydb`.`collection`
-- -----------------------------------------------------
CREATE TABLE `collection` (
  `id_collection` INT NOT NULL AUTO_INCREMENT,
  `nom_collection` TEXT(40) NULL,
  `num_collection` INT(11) NULL,
  `editeur_id_editeur` INT NOT NULL,
  PRIMARY KEY (`id_collection`, `editeur_id_editeur`),
  INDEX `fk_collection_editeur1_idx` (`editeur_id_editeur` ASC),
  CONSTRAINT `fk_collection_editeur1`
    FOREIGN KEY (`editeur_id_editeur`)
    REFERENCES `editeur` (`id_editeur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`livrephysique`
-- -----------------------------------------------------
CREATE TABLE `livrephysique` (
  `num_fiche` INT(11) NOT NULL,
  `cote` VARCHAR(15) NULL,
  `inventaire` TEXT(40) NULL,
  PRIMARY KEY (`num_fiche`));


-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE `type` (
  `idtype` INT NOT NULL AUTO_INCREMENT,
  `typelivre` VARCHAR(20) NULL,
  PRIMARY KEY (`idtype`));


-- -----------------------------------------------------
-- Table `mydb`.`langue`
-- -----------------------------------------------------
CREATE TABLE `langue` (
  `idlangue` INT NOT NULL AUTO_INCREMENT,
  `languelivre` VARCHAR(20) NULL,
  PRIMARY KEY (`idlangue`));


-- -----------------------------------------------------
-- Table `mydb`.`livre`
-- -----------------------------------------------------
CREATE `livre` (
  `id_livre` INT NOT NULL AUTO_INCREMENT,
  `auteur` TEXT(100) NULL,
  `titre` TEXT(100) NULL,
  `date_livre` INT(11) NULL,
  `isbn` VARCHAR(20) NULL,
  `ams` TEXT(20) NULL,
  `mots_clefs` TEXT(100) NULL,
  `editeur_id_editeur` INT NOT NULL,
  `catalogue_num_fiche` INT NOT NULL,
  `collection_id_collection` INT NOT NULL,
  `catalogue_num_fiche1` INT(11) NOT NULL,
  `type_idtype` INT NOT NULL,
  `langue_idlangue` INT NOT NULL,
  PRIMARY KEY (`id_livre`, `editeur_id_editeur`, `catalogue_num_fiche`, `collection_id_collection`, `catalogue_num_fiche1`, `type_idtype`, `langue_idlangue`),
  INDEX `fk_livre_collection1_idx` (`collection_id_collection` ASC),
  INDEX `fk_livre_catalogue1_idx` (`catalogue_num_fiche1` ASC),
  INDEX `fk_livre_type1_idx` (`type_idtype` ASC),
  INDEX `fk_livre_langue1_idx` (`langue_idlangue` ASC),
  CONSTRAINT `fk_livre_collection1`
    FOREIGN KEY (`collection_id_collection`)
    REFERENCES `collection` (`id_collection`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_catalogue1`
    FOREIGN KEY (`catalogue_num_fiche1`)
    REFERENCES `livrephysique` (`num_fiche`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_type1`
    FOREIGN KEY (`type_idtype`)
    REFERENCES `type` (`idtype`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livre_langue1`
    FOREIGN KEY (`langue_idlangue`)
    REFERENCES `langue` (`idlangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE `utilisateur` (
  `identifiant_utilisateur` VARCHAR(15) NOT NULL,
  `identite_personne` VARCHAR(50) NULL,
  `infosupp` TEXT(50) NULL,
  PRIMARY KEY (`identifiant_utilisateur`));


-- -----------------------------------------------------
-- Table `mydb`.`livre_propose`
-- -----------------------------------------------------
CREATE TABLE `livre_propose` (
  `id_livre_propose` INT NOT NULL AUTO_INCREMENT,
  `auteur` TEXT(100) NULL,
  `titre` TEXT(100) NULL,
  `editeur` TEXT(60) NULL,
  `etat` CHAR(1) NULL,
  `isbn` VARCHAR(20) NULL,
  PRIMARY KEY (`id_livre_propose`));


-- -----------------------------------------------------
-- Table `mydb`.`proposition`
-- -----------------------------------------------------
CREATE TABLE `proposition` (
  `id_proposition` INT NOT NULL AUTO_INCREMENT,
  `fournisseur` VARCHAR(15) NULL,
  `prix` INT(11) NULL,
  `date_commande` INT(10) NULL,
  `commentaire` TEXT(40) NULL,
  `utilisateur_identifiant_utilisateur` VARCHAR(15) NOT NULL,
  `livre_propose_id_livre_propose` INT NOT NULL,
  PRIMARY KEY (`id_proposition`, `utilisateur_identifiant_utilisateur`, `livre_propose_id_livre_propose`),
  INDEX `fk_proposition_utilisateur1_idx` (`utilisateur_identifiant_utilisateur` ASC),
  INDEX `fk_proposition_livre_propose1_idx` (`livre_propose_id_livre_propose` ASC),
  CONSTRAINT `fk_proposition_utilisateur1`
    FOREIGN KEY (`utilisateur_identifiant_utilisateur`)
    REFERENCES `utilisateur` (`identifiant_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposition_livre_propose1`
    FOREIGN KEY (`livre_propose_id_livre_propose`)
    REFERENCES `livre_propose` (`id_livre_propose`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`emprunt`
-- -----------------------------------------------------
CREATE TABLE `emprunt` (
  `id_emprunt` INT NOT NULL AUTO_INCREMENT,
  `date_emprunt` INT(10) NULL,
  `utilisateur_identifiant_utilisateur` VARCHAR(15) NOT NULL,
  `catalogue_num_fiche` INT(11) NOT NULL,
  PRIMARY KEY (`id_emprunt`, `utilisateur_identifiant_utilisateur`, `catalogue_num_fiche`),
  INDEX `fk_emprunt_utilisateur1_idx` (`utilisateur_identifiant_utilisateur` ASC),
  INDEX `fk_emprunt_catalogue1_idx` (`catalogue_num_fiche` ASC),
  CONSTRAINT `fk_emprunt_utilisateur1`
    FOREIGN KEY (`utilisateur_identifiant_utilisateur`)
    REFERENCES `utilisateur` (`identifiant_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprunt_catalogue1`
    FOREIGN KEY (`catalogue_num_fiche`)
    REFERENCES `livrephysique` (`num_fiche`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
